container:
  image: node:latest

env:
  GITHUB_TOKEN: ENCRYPTED[6435caa35f87b9e2b38a6e1a191b72443cc2836171f4c7422860059c675ef5679dc3c8b64e4329fb89700b045f39615f]

install_task:
  install_script: yarn install

build_task:
  depends_on:
    - install
  build_script: yarn build

test_task:
  depends_on:
    - build
  test_script: yarn test
